config_name: e2c_config3
loss:
  beta: 0.01
  kld_anneal_mode: linear
  lambda: 0.01
  recon_mult: 10000.0
train:
  batch_size: 32
  dataset: reacher
  device: cuda:2
  eval: true
  num_epochs: 10
  plot_freq: 10000
  render: false
  save: true
  train_ratio: 0.95
trans:
  alpha: 0.0001
  latent_size: 4
  past_length: 1
  pred_length: 1
  weight_decay: 0.0001
vae:
  dec_kernel_size: 4
  enc_kernel_size: 3
  enc_latent_size: 256
  pad: 1
  stride: 2
